// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: carts.sql

package sqlc

import (
	"context"
)

const addToCart = `-- name: AddToCart :one
insert into cart(user_id,product_id,quantity)
values ($1,$2,$3)
returning id, user_id, product_id, quantity, created_at, updated_at
`

type AddToCartParams struct {
	UserID    int32  `json:"user_id"`
	ProductID int32  `json:"product_id"`
	Quantity  *int32 `json:"quantity"`
}

func (q *Queries) AddToCart(ctx context.Context, arg AddToCartParams) (Cart, error) {
	row := q.db.QueryRow(ctx, addToCart, arg.UserID, arg.ProductID, arg.Quantity)
	var i Cart
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProductID,
		&i.Quantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const existsProductId = `-- name: ExistsProductId :one
SELECT
    (EXISTS (
        SELECT 1
        FROM cart
        WHERE product_id = $1::int
            AND user_id = $2::int
    )) AS exists_
`

type ExistsProductIdParams struct {
	ProductID int32 `json:"product_id"`
	UserID    int32 `json:"user_id"`
}

func (q *Queries) ExistsProductId(ctx context.Context, arg ExistsProductIdParams) (bool, error) {
	row := q.db.QueryRow(ctx, existsProductId, arg.ProductID, arg.UserID)
	var exists_ bool
	err := row.Scan(&exists_)
	return exists_, err
}

const updateCart = `-- name: UpdateCart :one
update cart
set quantity = quantity + $1::int
where user_id = $2::int
and product_id = $3::int
returning id, user_id, product_id, quantity, created_at, updated_at
`

type UpdateCartParams struct {
	Quantity  int32 `json:"quantity"`
	UserID    int32 `json:"user_id"`
	ProductID int32 `json:"product_id"`
}

func (q *Queries) UpdateCart(ctx context.Context, arg UpdateCartParams) (Cart, error) {
	row := q.db.QueryRow(ctx, updateCart, arg.Quantity, arg.UserID, arg.ProductID)
	var i Cart
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProductID,
		&i.Quantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
