// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

type AttributeConfig struct {
	ID           int32   `json:"id"`
	AttrName     string  `json:"attr_name"`
	AttrValue    string  `json:"attr_value"`
	DisplayLabel *string `json:"display_label"`
	ColorCode    *string `json:"color_code"`
}

type Brand struct {
	ID        int32            `json:"id"`
	Name      string           `json:"name"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type Cart struct {
	ID        int64            `json:"id"`
	UserID    int32            `json:"user_id"`
	Quantity  *int32           `json:"quantity"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
	VariantID int32            `json:"variant_id"`
}

type Category struct {
	ID        int32            `json:"id"`
	Name      string           `json:"name"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type Order struct {
	ID              int32            `json:"id"`
	UserID          int32            `json:"user_id"`
	Name            string           `json:"name"`
	Email           string           `json:"email"`
	Phone           string           `json:"phone"`
	Address         string           `json:"address"`
	PaymentMethodID int32            `json:"payment_method_id"`
	Subtotal        pgtype.Numeric   `json:"subtotal"`
	ShippingPrice   pgtype.Numeric   `json:"shipping_price"`
	Tax             pgtype.Numeric   `json:"tax"`
	TotalAmount     pgtype.Numeric   `json:"total_amount"`
	Status          string           `json:"status"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
	UpdatedAt       pgtype.Timestamp `json:"updated_at"`
	PaymentStatus   string           `json:"payment_status"`
	TransactionID   *string          `json:"transaction_id"`
	DeliveredAt     pgtype.Timestamp `json:"delivered_at"`
	AmountItem      *int32           `json:"amount_item"`
}

type OrderItem struct {
	ID               int32            `json:"id"`
	OrderID          int32            `json:"order_id"`
	VariantID        int32            `json:"variant_id"`
	Quantity         int32            `json:"quantity"`
	Price            pgtype.Numeric   `json:"price"`
	ProductName      string           `json:"product_name"`
	ProductThumbnail *string          `json:"product_thumbnail"`
	CreatedAt        pgtype.Timestamp `json:"created_at"`
}

type OrderStatusHistory struct {
	ID        int32            `json:"id"`
	OrderID   int32            `json:"order_id"`
	Status    string           `json:"status"`
	Note      *string          `json:"note"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type PaymentMethod struct {
	ID          int32   `json:"id"`
	Name        string  `json:"name"`
	Description *string `json:"description"`
	IsActive    *bool   `json:"is_active"`
}

type PendingOrder struct {
	ID              int32            `json:"id"`
	UserID          int32            `json:"user_id"`
	Name            string           `json:"name"`
	Email           string           `json:"email"`
	Phone           string           `json:"phone"`
	PaymentMethodID int32            `json:"payment_method_id"`
	Address         string           `json:"address"`
	Otp             string           `json:"otp"`
	OtpExpiresAt    pgtype.Timestamp `json:"otp_expires_at"`
	Subtotal        pgtype.Numeric   `json:"subtotal"`
	TotalAmount     pgtype.Numeric   `json:"total_amount"`
	ShippingPrice   pgtype.Numeric   `json:"shipping_price"`
	Tax             pgtype.Numeric   `json:"tax"`
	Status          *string          `json:"status"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
	AmountItem      *int32           `json:"amount_item"`
}

type PendingOrderItem struct {
	ID             int32          `json:"id"`
	PendingOrderID int32          `json:"pending_order_id"`
	VariantID      int32          `json:"variant_id"`
	Quantity       int32          `json:"quantity"`
	Price          pgtype.Numeric `json:"price"`
}

type Product struct {
	ID               int64            `json:"id"`
	Name             string           `json:"name"`
	Slug             string           `json:"slug"`
	BrandID          *int32           `json:"brand_id"`
	CategoryID       *int32           `json:"category_id"`
	Description      *string          `json:"description"`
	ShortDescription *string          `json:"short_description"`
	Status           *string          `json:"status"`
	CreatedAt        pgtype.Timestamp `json:"created_at"`
	UpdatedAt        pgtype.Timestamp `json:"updated_at"`
	Thumbnail        string           `json:"thumbnail"`
	HasVariants      *bool            `json:"has_variants"`
}

type ProductImage struct {
	ID        int32  `json:"id"`
	ProductID int64  `json:"product_id"`
	ImageUrl  string `json:"image_url"`
}

type ProductSpecification struct {
	ID           int32  `json:"id"`
	ProductID    int64  `json:"product_id"`
	SpecKey      string `json:"spec_key"`
	SpecValue    string `json:"spec_value"`
	DisplayOrder *int32 `json:"display_order"`
}

type ProductVariant struct {
	ID            int32            `json:"id"`
	ProductID     int64            `json:"product_id"`
	Sku           *string          `json:"sku"`
	Attributes    json.RawMessage  `json:"attributes"`
	Price         pgtype.Numeric   `json:"price"`
	StockQuantity int32            `json:"stock_quantity"`
	Images        []byte           `json:"images"`
	IsActive      *bool            `json:"is_active"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
}

type User struct {
	ID          int32            `json:"id"`
	Name        string           `json:"name"`
	Email       string           `json:"email"`
	Password    string           `json:"password"`
	Phone       *string          `json:"phone"`
	Address     *string          `json:"address"`
	Role        *string          `json:"role"`
	IsActive    *bool            `json:"is_active"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
	UserUuid    pgtype.UUID      `json:"user_uuid"`
	NameSearch  *string          `json:"name_search"`
	EmailSearch *string          `json:"email_search"`
}
