// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: order_status_history.sql

package sqlc

import (
	"context"
)

const createOrderStatusHistory = `-- name: CreateOrderStatusHistory :one
insert into order_status_history(order_id,status,note)
values ($1,$2,$3)
returning id, order_id, status, note, created_at
`

type CreateOrderStatusHistoryParams struct {
	OrderID int32   `json:"order_id"`
	Status  string  `json:"status"`
	Note    *string `json:"note"`
}

func (q *Queries) CreateOrderStatusHistory(ctx context.Context, arg CreateOrderStatusHistoryParams) (OrderStatusHistory, error) {
	row := q.db.QueryRow(ctx, createOrderStatusHistory, arg.OrderID, arg.Status, arg.Note)
	var i OrderStatusHistory
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.Status,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}
