// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: order.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders(user_id,name,email,phone,payment_method_id,address,subtotal,total_amount,shipping_price,tax,status)
VALUES ($1,$2,$3,$4,$5,$6,
        $7::NUMERIC(10,2),
        $8::NUMERIC(10,2),
        $9::NUMERIC(10,2),
        $10::NUMERIC(10,2),
        $11
       )
    RETURNING id, user_id, name, email, phone, address, payment_method_id, subtotal, shipping_price, tax, total_amount, status, created_at, updated_at, payment_status, transaction_id, delivered_at
`

type CreateOrderParams struct {
	UserID          int32          `json:"user_id"`
	Name            string         `json:"name"`
	Email           string         `json:"email"`
	Phone           string         `json:"phone"`
	PaymentMethodID int32          `json:"payment_method_id"`
	Address         string         `json:"address"`
	Subtotal        pgtype.Numeric `json:"subtotal"`
	TotalAmount     pgtype.Numeric `json:"total_amount"`
	ShippingPrice   pgtype.Numeric `json:"shipping_price"`
	Tax             pgtype.Numeric `json:"tax"`
	Status          string         `json:"status"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.UserID,
		arg.Name,
		arg.Email,
		arg.Phone,
		arg.PaymentMethodID,
		arg.Address,
		arg.Subtotal,
		arg.TotalAmount,
		arg.ShippingPrice,
		arg.Tax,
		arg.Status,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Address,
		&i.PaymentMethodID,
		&i.Subtotal,
		&i.ShippingPrice,
		&i.Tax,
		&i.TotalAmount,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PaymentStatus,
		&i.TransactionID,
		&i.DeliveredAt,
	)
	return i, err
}
