// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: order_item.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addOrderItem = `-- name: AddOrderItem :one
insert into order_items(order_id,variant_id,quantity,price,product_name,product_thumbnail)
values ($1,$2,$3,$4,$5,$6)
returning id, order_id, variant_id, quantity, price, product_name, product_thumbnail, created_at
`

type AddOrderItemParams struct {
	OrderID          int32          `json:"order_id"`
	VariantID        int32          `json:"variant_id"`
	Quantity         int32          `json:"quantity"`
	Price            pgtype.Numeric `json:"price"`
	ProductName      string         `json:"product_name"`
	ProductThumbnail *string        `json:"product_thumbnail"`
}

func (q *Queries) AddOrderItem(ctx context.Context, arg AddOrderItemParams) (OrderItem, error) {
	row := q.db.QueryRow(ctx, addOrderItem,
		arg.OrderID,
		arg.VariantID,
		arg.Quantity,
		arg.Price,
		arg.ProductName,
		arg.ProductThumbnail,
	)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.VariantID,
		&i.Quantity,
		&i.Price,
		&i.ProductName,
		&i.ProductThumbnail,
		&i.CreatedAt,
	)
	return i, err
}

const getCountItem = `-- name: GetCountItem :one
SELECT COUNT(*) AS count
FROM order_items o
WHERE o.order_id = $1
GROUP BY o.order_id
`

func (q *Queries) GetCountItem(ctx context.Context, id int32) (int64, error) {
	row := q.db.QueryRow(ctx, getCountItem, id)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getOrderItemByUserId = `-- name: GetOrderItemByUserId :many
SELECT
    -- order info
    o.id AS order_id,
    o.name AS customer_name,
    o.phone,
    o.address,
    o.subtotal,
    o.shipping_price,
    o.tax,
    o.total_amount,
    o.status,
    o.created_at AS order_created_at,

    -- item info
    oi.variant_id,
    oi.quantity,
    oi.price AS item_price,
    oi.product_name,
    oi.product_thumbnail,
    oi.created_at AS item_created_at,

    -- payment method
    p.name AS payment_method_name

FROM order_items oi
         JOIN orders o ON oi.order_id = o.id
         JOIN payment_methods p ON p.id = o.payment_method_id
WHERE o.user_id = $1::int
ORDER BY oi.created_at DESC
`

type GetOrderItemByUserIdRow struct {
	OrderID           int32            `json:"order_id"`
	CustomerName      string           `json:"customer_name"`
	Phone             string           `json:"phone"`
	Address           string           `json:"address"`
	Subtotal          pgtype.Numeric   `json:"subtotal"`
	ShippingPrice     pgtype.Numeric   `json:"shipping_price"`
	Tax               pgtype.Numeric   `json:"tax"`
	TotalAmount       pgtype.Numeric   `json:"total_amount"`
	Status            string           `json:"status"`
	OrderCreatedAt    pgtype.Timestamp `json:"order_created_at"`
	VariantID         int32            `json:"variant_id"`
	Quantity          int32            `json:"quantity"`
	ItemPrice         pgtype.Numeric   `json:"item_price"`
	ProductName       string           `json:"product_name"`
	ProductThumbnail  *string          `json:"product_thumbnail"`
	ItemCreatedAt     pgtype.Timestamp `json:"item_created_at"`
	PaymentMethodName string           `json:"payment_method_name"`
}

func (q *Queries) GetOrderItemByUserId(ctx context.Context, id int32) ([]GetOrderItemByUserIdRow, error) {
	rows, err := q.db.Query(ctx, getOrderItemByUserId, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetOrderItemByUserIdRow{}
	for rows.Next() {
		var i GetOrderItemByUserIdRow
		if err := rows.Scan(
			&i.OrderID,
			&i.CustomerName,
			&i.Phone,
			&i.Address,
			&i.Subtotal,
			&i.ShippingPrice,
			&i.Tax,
			&i.TotalAmount,
			&i.Status,
			&i.OrderCreatedAt,
			&i.VariantID,
			&i.Quantity,
			&i.ItemPrice,
			&i.ProductName,
			&i.ProductThumbnail,
			&i.ItemCreatedAt,
			&i.PaymentMethodName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
