// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: payment_method.sql

package sqlc

import (
	"context"
)

const getAllPayment = `-- name: GetAllPayment :many
select id, name, description, is_active
from payment_methods
`

func (q *Queries) GetAllPayment(ctx context.Context) ([]PaymentMethod, error) {
	rows, err := q.db.Query(ctx, getAllPayment)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PaymentMethod{}
	for rows.Next() {
		var i PaymentMethod
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
