// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: pending_orders.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPendingOrder = `-- name: CreatePendingOrder :one
INSERT INTO pending_orders(user_id,name,email,phone,payment_method_id,address,otp,otp_expires_at,subtotal,total_amount,shipping_price,tax,status,amount_item)
VALUES ($1,$2,$3,$4,$5,$6,$7,
           $8,
           $9::NUMERIC(10,2),
           $10::NUMERIC(10,2),
           $11::NUMERIC(10,2),
           $12::NUMERIC(10,2),
           $13,
            $14
       )
    RETURNING id, user_id, name, email, phone, payment_method_id, address, otp, otp_expires_at, subtotal, total_amount, shipping_price, tax, status, created_at, amount_item
`

type CreatePendingOrderParams struct {
	UserID          int32            `json:"user_id"`
	Name            string           `json:"name"`
	Email           string           `json:"email"`
	Phone           string           `json:"phone"`
	PaymentMethodID int32            `json:"payment_method_id"`
	Address         string           `json:"address"`
	Otp             string           `json:"otp"`
	OtpExpiresAt    pgtype.Timestamp `json:"otp_expires_at"`
	Subtotal        pgtype.Numeric   `json:"subtotal"`
	TotalAmount     pgtype.Numeric   `json:"total_amount"`
	ShippingPrice   pgtype.Numeric   `json:"shipping_price"`
	Tax             pgtype.Numeric   `json:"tax"`
	Status          *string          `json:"status"`
	AmountItem      *int32           `json:"amount_item"`
}

func (q *Queries) CreatePendingOrder(ctx context.Context, arg CreatePendingOrderParams) (PendingOrder, error) {
	row := q.db.QueryRow(ctx, createPendingOrder,
		arg.UserID,
		arg.Name,
		arg.Email,
		arg.Phone,
		arg.PaymentMethodID,
		arg.Address,
		arg.Otp,
		arg.OtpExpiresAt,
		arg.Subtotal,
		arg.TotalAmount,
		arg.ShippingPrice,
		arg.Tax,
		arg.Status,
		arg.AmountItem,
	)
	var i PendingOrder
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.PaymentMethodID,
		&i.Address,
		&i.Otp,
		&i.OtpExpiresAt,
		&i.Subtotal,
		&i.TotalAmount,
		&i.ShippingPrice,
		&i.Tax,
		&i.Status,
		&i.CreatedAt,
		&i.AmountItem,
	)
	return i, err
}

const getPOrderById = `-- name: GetPOrderById :one
select id, user_id, name, email, phone, payment_method_id, address, otp, otp_expires_at, subtotal, total_amount, shipping_price, tax, status, created_at, amount_item
from pending_orders
where id = $1::int
`

func (q *Queries) GetPOrderById(ctx context.Context, id int32) (PendingOrder, error) {
	row := q.db.QueryRow(ctx, getPOrderById, id)
	var i PendingOrder
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.PaymentMethodID,
		&i.Address,
		&i.Otp,
		&i.OtpExpiresAt,
		&i.Subtotal,
		&i.TotalAmount,
		&i.ShippingPrice,
		&i.Tax,
		&i.Status,
		&i.CreatedAt,
		&i.AmountItem,
	)
	return i, err
}
