// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: pending_order_item.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPendingOrderItem = `-- name: CreatePendingOrderItem :one
insert into pending_order_items(pending_order_id,product_id,quantity,price)
values ($1,$2,$3,$4)
returning id, pending_order_id, product_id, quantity, price
`

type CreatePendingOrderItemParams struct {
	PendingOrderID int32          `json:"pending_order_id"`
	ProductID      int32          `json:"product_id"`
	Quantity       int32          `json:"quantity"`
	Price          pgtype.Numeric `json:"price"`
}

func (q *Queries) CreatePendingOrderItem(ctx context.Context, arg CreatePendingOrderItemParams) (PendingOrderItem, error) {
	row := q.db.QueryRow(ctx, createPendingOrderItem,
		arg.PendingOrderID,
		arg.ProductID,
		arg.Quantity,
		arg.Price,
	)
	var i PendingOrderItem
	err := row.Scan(
		&i.ID,
		&i.PendingOrderID,
		&i.ProductID,
		&i.Quantity,
		&i.Price,
	)
	return i, err
}

const getByPOrderItemId = `-- name: GetByPOrderItemId :many
select id, pending_order_id, product_id, quantity, price
from pending_order_items
where pending_order_id = $1::int
`

func (q *Queries) GetByPOrderItemId(ctx context.Context, id int32) ([]PendingOrderItem, error) {
	rows, err := q.db.Query(ctx, getByPOrderItemId, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PendingOrderItem{}
	for rows.Next() {
		var i PendingOrderItem
		if err := rows.Scan(
			&i.ID,
			&i.PendingOrderID,
			&i.ProductID,
			&i.Quantity,
			&i.Price,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCountItems = `-- name: GetCountItems :one
select count(*) as count
from pending_order_items
where pending_order_id = $1
group by pending_order_id
`

func (q *Queries) GetCountItems(ctx context.Context, id int32) (int64, error) {
	row := q.db.QueryRow(ctx, getCountItems, id)
	var count int64
	err := row.Scan(&count)
	return count, err
}
