// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: product_images.sql

package sqlc

import (
	"context"
)

const getImagesByProductId = `-- name: GetImagesByProductId :many
select p.image_url
from product_images p
where product_id = $1::int
`

func (q *Queries) GetImagesByProductId(ctx context.Context, id int32) ([]string, error) {
	rows, err := q.db.Query(ctx, getImagesByProductId, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var image_url string
		if err := rows.Scan(&image_url); err != nil {
			return nil, err
		}
		items = append(items, image_url)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveAndUploadImg = `-- name: SaveAndUploadImg :one
insert into product_images (product_id,image_url)
values ($1,$2)
returning id, product_id, image_url
`

type SaveAndUploadImgParams struct {
	ProductID int64  `json:"product_id"`
	ImageUrl  string `json:"image_url"`
}

func (q *Queries) SaveAndUploadImg(ctx context.Context, arg SaveAndUploadImgParams) (ProductImage, error) {
	row := q.db.QueryRow(ctx, saveAndUploadImg, arg.ProductID, arg.ImageUrl)
	var i ProductImage
	err := row.Scan(&i.ID, &i.ProductID, &i.ImageUrl)
	return i, err
}
