// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: products.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countProduct = `-- name: CountProduct :one
select count(*)
from products
where created_at is not null
and (
    $1::text = ''
    or name ilike '%' || $1::text ||'%'
    or sku ilike '%' || $1::text ||'%'
    or slug ilike '%' || $1::text ||'%'
    )
and
(
    price >= coalesce($2::int,0)
    and price <= coalesce($3::int,99999999)
    )
    and(
    $4::text =''
    OR status = $4::text
    )
and(
    $5::int = 0
    or category_id = $5::int
    )
`

type CountProductParams struct {
	Search     string `json:"search"`
	MinPrice   int32  `json:"min_price"`
	MaxPrice   int32  `json:"max_price"`
	Status     string `json:"status"`
	CategoryID int32  `json:"category_id"`
}

func (q *Queries) CountProduct(ctx context.Context, arg CountProductParams) (int64, error) {
	row := q.db.QueryRow(ctx, countProduct,
		arg.Search,
		arg.MinPrice,
		arg.MaxPrice,
		arg.Status,
		arg.CategoryID,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProduct = `-- name: CreateProduct :one
insert into products(name,slug,sku,brand_id,category_id,description,short_description,price,discount_price,stock_quantity)
values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)
returning id, name, slug, sku, brand_id, category_id, description, short_description, price, discount_price, stock_quantity, status, created_at, updated_at
`

type CreateProductParams struct {
	Name             string         `json:"name"`
	Slug             string         `json:"slug"`
	Sku              string         `json:"sku"`
	BrandID          *int32         `json:"brand_id"`
	CategoryID       *int32         `json:"category_id"`
	Description      *string        `json:"description"`
	ShortDescription *string        `json:"short_description"`
	Price            pgtype.Numeric `json:"price"`
	DiscountPrice    pgtype.Numeric `json:"discount_price"`
	StockQuantity    *int32         `json:"stock_quantity"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.Name,
		arg.Slug,
		arg.Sku,
		arg.BrandID,
		arg.CategoryID,
		arg.Description,
		arg.ShortDescription,
		arg.Price,
		arg.DiscountPrice,
		arg.StockQuantity,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Sku,
		&i.BrandID,
		&i.CategoryID,
		&i.Description,
		&i.ShortDescription,
		&i.Price,
		&i.DiscountPrice,
		&i.StockQuantity,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAllProductByFilter = `-- name: GetAllProductByFilter :many
select id, name, slug, sku, brand_id, category_id, description, short_description, price, discount_price, stock_quantity, status, created_at, updated_at
from products
where created_at is not null
and(
    $3::text = ''
    or $3::text ilike '%'||sku||'%'
     or $3::text ilike '%'||slug||'%'
     or $3::text ilike '%'||name||'%'
    )

and (
    price >= coalesce($4::int,0)
and price <= coalesce($5::int,99999999)
    )
and(
    $6::text ='' OR status = $6::text
    )

and(
     $7::int = 0
    or category_id = $7::int
    )
order by updated_at desc
limit $1
offset $2
`

type GetAllProductByFilterParams struct {
	Limit      int32  `json:"limit"`
	Offset     int32  `json:"offset"`
	Search     string `json:"search"`
	MinPrice   int32  `json:"min_price"`
	MaxPrice   int32  `json:"max_price"`
	Status     string `json:"status"`
	CategoryID int32  `json:"category_id"`
}

func (q *Queries) GetAllProductByFilter(ctx context.Context, arg GetAllProductByFilterParams) ([]Product, error) {
	rows, err := q.db.Query(ctx, getAllProductByFilter,
		arg.Limit,
		arg.Offset,
		arg.Search,
		arg.MinPrice,
		arg.MaxPrice,
		arg.Status,
		arg.CategoryID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Sku,
			&i.BrandID,
			&i.CategoryID,
			&i.Description,
			&i.ShortDescription,
			&i.Price,
			&i.DiscountPrice,
			&i.StockQuantity,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductById = `-- name: GetProductById :one
select id, name, slug, sku, brand_id, category_id, description, short_description, price, discount_price, stock_quantity, status, created_at, updated_at
from products
where created_at is not null
and id = $1::int
`

func (q *Queries) GetProductById(ctx context.Context, id int32) (Product, error) {
	row := q.db.QueryRow(ctx, getProductById, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Sku,
		&i.BrandID,
		&i.CategoryID,
		&i.Description,
		&i.ShortDescription,
		&i.Price,
		&i.DiscountPrice,
		&i.StockQuantity,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
