// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: products.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countProduct = `-- name: CountProduct :one
select count(*)
from products
where created_at is not null
and (
    $1::text = ''
    or name ILIKE '%' || $1::text ||'%'
    or sku ILIKE '%' || $1::text ||'%'
    or slug ILIKE '%' || $1::text ||'%'
    )
and
(
    price >= coalesce($2::int,0)
    and price <= coalesce($3::int,99999999)
    )
    and(
    $4::text =''
    OR status = $4::text
    )
and(
    $5::int = 0
    or category_id = $5::int
    )
`

type CountProductParams struct {
	Search     string `json:"search"`
	MinPrice   int32  `json:"min_price"`
	MaxPrice   int32  `json:"max_price"`
	Status     string `json:"status"`
	CategoryID int32  `json:"category_id"`
}

func (q *Queries) CountProduct(ctx context.Context, arg CountProductParams) (int64, error) {
	row := q.db.QueryRow(ctx, countProduct,
		arg.Search,
		arg.MinPrice,
		arg.MaxPrice,
		arg.Status,
		arg.CategoryID,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProduct = `-- name: CreateProduct :one
insert into products(name,slug,sku,brand_id,category_id,description,short_description,price,discount_price,stock_quantity)
values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)
returning id, name, slug, sku, brand_id, category_id, description, short_description, price, discount_price, stock_quantity, status, created_at, updated_at, thumbnail
`

type CreateProductParams struct {
	Name             string         `json:"name"`
	Slug             string         `json:"slug"`
	Sku              string         `json:"sku"`
	BrandID          *int32         `json:"brand_id"`
	CategoryID       *int32         `json:"category_id"`
	Description      *string        `json:"description"`
	ShortDescription *string        `json:"short_description"`
	Price            pgtype.Numeric `json:"price"`
	DiscountPrice    pgtype.Numeric `json:"discount_price"`
	StockQuantity    *int32         `json:"stock_quantity"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.Name,
		arg.Slug,
		arg.Sku,
		arg.BrandID,
		arg.CategoryID,
		arg.Description,
		arg.ShortDescription,
		arg.Price,
		arg.DiscountPrice,
		arg.StockQuantity,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Sku,
		&i.BrandID,
		&i.CategoryID,
		&i.Description,
		&i.ShortDescription,
		&i.Price,
		&i.DiscountPrice,
		&i.StockQuantity,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Thumbnail,
	)
	return i, err
}

const getAllProductByFilter = `-- name: GetAllProductByFilter :many
select p.id,
       p.name,
       p.sku,
       p.slug,
       p.description,
       p.short_description,
       p.price,
       p.discount_price,
       p.stock_quantity,
       p.thumbnail,
       p.status,
        b.name as brand_name,
        c.name as category_name

from products p
left join brand b on b.id = p.brand_id
left join categories c on c.id = p.category_id
where p.created_at is not null
and(
    $3::text = ''
    or p.name ILIKE '%' || $3::text ||'%'
    or p.sku ILIKE '%' || $3::text ||'%'
    or p.slug ILIKE '%' || $3::text ||'%'
    )

and (
    p.price >= coalesce($4::int,0)
and p.price <= coalesce($5::int,99999999)
    )
and(
    $6::text ='' OR p.status = $6::text
    )
and(
    $7::int =0
    or p.brand_id = $7::int
    )
and(
     $8::int = 0
    or p.category_id = $8::int
    )
order by
    CASE WHEN $9::text = 'price_asc' THEN p.price END asc,
    CASE WHEN $9::text = 'price_desc' THEN p.price END desc ,
    CASE WHEN $9::text = 'newest' THEN p.updated_at END desc,
    p.updated_at desc
limit $1
offset $2
`

type GetAllProductByFilterParams struct {
	Limit      int32  `json:"limit"`
	Offset     int32  `json:"offset"`
	Search     string `json:"search"`
	MinPrice   int32  `json:"min_price"`
	MaxPrice   int32  `json:"max_price"`
	Status     string `json:"status"`
	BrandID    int32  `json:"brand_id"`
	CategoryID int32  `json:"category_id"`
	SortBy     string `json:"sort_by"`
}

type GetAllProductByFilterRow struct {
	ID               int64          `json:"id"`
	Name             string         `json:"name"`
	Sku              string         `json:"sku"`
	Slug             string         `json:"slug"`
	Description      *string        `json:"description"`
	ShortDescription *string        `json:"short_description"`
	Price            pgtype.Numeric `json:"price"`
	DiscountPrice    pgtype.Numeric `json:"discount_price"`
	StockQuantity    *int32         `json:"stock_quantity"`
	Thumbnail        string         `json:"thumbnail"`
	Status           *string        `json:"status"`
	BrandName        *string        `json:"brand_name"`
	CategoryName     *string        `json:"category_name"`
}

func (q *Queries) GetAllProductByFilter(ctx context.Context, arg GetAllProductByFilterParams) ([]GetAllProductByFilterRow, error) {
	rows, err := q.db.Query(ctx, getAllProductByFilter,
		arg.Limit,
		arg.Offset,
		arg.Search,
		arg.MinPrice,
		arg.MaxPrice,
		arg.Status,
		arg.BrandID,
		arg.CategoryID,
		arg.SortBy,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAllProductByFilterRow{}
	for rows.Next() {
		var i GetAllProductByFilterRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Sku,
			&i.Slug,
			&i.Description,
			&i.ShortDescription,
			&i.Price,
			&i.DiscountPrice,
			&i.StockQuantity,
			&i.Thumbnail,
			&i.Status,
			&i.BrandName,
			&i.CategoryName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductByCategoryId = `-- name: GetProductByCategoryId :many
select p.id,
       p.name,
       p.sku,
       p.slug,
       p.description,
       p.short_description,
       p.price,
       p.discount_price,
       p.stock_quantity,
       p.thumbnail,
       p.status,
       b.name as brand_name,
       c.name as category_name
from products p
left join brand b on b.id = p.brand_id
left join categories c on c.id = p.category_id
where p.created_at is not null
and(
    p.category_id = $1::int
)
`

type GetProductByCategoryIdRow struct {
	ID               int64          `json:"id"`
	Name             string         `json:"name"`
	Sku              string         `json:"sku"`
	Slug             string         `json:"slug"`
	Description      *string        `json:"description"`
	ShortDescription *string        `json:"short_description"`
	Price            pgtype.Numeric `json:"price"`
	DiscountPrice    pgtype.Numeric `json:"discount_price"`
	StockQuantity    *int32         `json:"stock_quantity"`
	Thumbnail        string         `json:"thumbnail"`
	Status           *string        `json:"status"`
	BrandName        *string        `json:"brand_name"`
	CategoryName     *string        `json:"category_name"`
}

func (q *Queries) GetProductByCategoryId(ctx context.Context, id int32) ([]GetProductByCategoryIdRow, error) {
	rows, err := q.db.Query(ctx, getProductByCategoryId, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetProductByCategoryIdRow{}
	for rows.Next() {
		var i GetProductByCategoryIdRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Sku,
			&i.Slug,
			&i.Description,
			&i.ShortDescription,
			&i.Price,
			&i.DiscountPrice,
			&i.StockQuantity,
			&i.Thumbnail,
			&i.Status,
			&i.BrandName,
			&i.CategoryName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductById = `-- name: GetProductById :one
select id, name, slug, sku, brand_id, category_id, description, short_description, price, discount_price, stock_quantity, status, created_at, updated_at, thumbnail
from products
where created_at is not null
and id = $1::int
`

func (q *Queries) GetProductById(ctx context.Context, id int32) (Product, error) {
	row := q.db.QueryRow(ctx, getProductById, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Sku,
		&i.BrandID,
		&i.CategoryID,
		&i.Description,
		&i.ShortDescription,
		&i.Price,
		&i.DiscountPrice,
		&i.StockQuantity,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Thumbnail,
	)
	return i, err
}

const getProductBySlug = `-- name: GetProductBySlug :one
select p.id,
       p.name,
       p.sku,
       p.slug,
       p.description,
       p.short_description,
       p.price,
       p.discount_price,
       p.stock_quantity,
       p.thumbnail,
       p.status,
       b.name as brand_name,
       c.name as category_name
from products p
         left join brand b on b.id = p.brand_id
         left join categories c on c.id = p.category_id
where p.created_at is not null
  and(
    p.slug = $1::text
    )
`

type GetProductBySlugRow struct {
	ID               int64          `json:"id"`
	Name             string         `json:"name"`
	Sku              string         `json:"sku"`
	Slug             string         `json:"slug"`
	Description      *string        `json:"description"`
	ShortDescription *string        `json:"short_description"`
	Price            pgtype.Numeric `json:"price"`
	DiscountPrice    pgtype.Numeric `json:"discount_price"`
	StockQuantity    *int32         `json:"stock_quantity"`
	Thumbnail        string         `json:"thumbnail"`
	Status           *string        `json:"status"`
	BrandName        *string        `json:"brand_name"`
	CategoryName     *string        `json:"category_name"`
}

func (q *Queries) GetProductBySlug(ctx context.Context, slug string) (GetProductBySlugRow, error) {
	row := q.db.QueryRow(ctx, getProductBySlug, slug)
	var i GetProductBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Sku,
		&i.Slug,
		&i.Description,
		&i.ShortDescription,
		&i.Price,
		&i.DiscountPrice,
		&i.StockQuantity,
		&i.Thumbnail,
		&i.Status,
		&i.BrandName,
		&i.CategoryName,
	)
	return i, err
}

const getTop8ProductSeller = `-- name: GetTop8ProductSeller :many
select  p.id,
        p.name,
        p.price,
        p.discount_price,
        p.thumbnail,
        p.slug
from products p
where category_id = $1
order by discount_price desc
    limit 8
`

type GetTop8ProductSellerRow struct {
	ID            int64          `json:"id"`
	Name          string         `json:"name"`
	Price         pgtype.Numeric `json:"price"`
	DiscountPrice pgtype.Numeric `json:"discount_price"`
	Thumbnail     string         `json:"thumbnail"`
	Slug          string         `json:"slug"`
}

func (q *Queries) GetTop8ProductSeller(ctx context.Context, cateID *int32) ([]GetTop8ProductSellerRow, error) {
	rows, err := q.db.Query(ctx, getTop8ProductSeller, cateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTop8ProductSellerRow{}
	for rows.Next() {
		var i GetTop8ProductSellerRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Price,
			&i.DiscountPrice,
			&i.Thumbnail,
			&i.Slug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateThumbnail = `-- name: UpdateThumbnail :one
update products
set thumbnail = $1::text
where id = $2::int
and created_at is not null
returning id, name, slug, sku, brand_id, category_id, description, short_description, price, discount_price, stock_quantity, status, created_at, updated_at, thumbnail
`

type UpdateThumbnailParams struct {
	Thumbnail string `json:"thumbnail"`
	ID        int32  `json:"id"`
}

func (q *Queries) UpdateThumbnail(ctx context.Context, arg UpdateThumbnailParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateThumbnail, arg.Thumbnail, arg.ID)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Sku,
		&i.BrandID,
		&i.CategoryID,
		&i.Description,
		&i.ShortDescription,
		&i.Price,
		&i.DiscountPrice,
		&i.StockQuantity,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Thumbnail,
	)
	return i, err
}
