// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: product_images.sql

package sqlc

import (
	"context"
)

const saveAndUploadImg = `-- name: SaveAndUploadImg :one
insert into product_images (product_id,image_url)
values ($1,$2)
returning id, product_id, image_url
`

type SaveAndUploadImgParams struct {
	ProductID int64  `json:"product_id"`
	ImageUrl  string `json:"image_url"`
}

func (q *Queries) SaveAndUploadImg(ctx context.Context, arg SaveAndUploadImgParams) (ProductImage, error) {
	row := q.db.QueryRow(ctx, saveAndUploadImg, arg.ProductID, arg.ImageUrl)
	var i ProductImage
	err := row.Scan(&i.ID, &i.ProductID, &i.ImageUrl)
	return i, err
}
