// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddToCart(ctx context.Context, arg AddToCartParams) (Cart, error)
	CountProduct(ctx context.Context, arg CountProductParams) (int64, error)
	CountUser(ctx context.Context, arg CountUserParams) (int64, error)
	CreateCategory(ctx context.Context, name string) (Category, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	ExistsProductId(ctx context.Context, arg ExistsProductIdParams) (bool, error)
	FindByEmail(ctx context.Context, email string) (User, error)
	GetAll(ctx context.Context) ([]Brand, error)
	GetAllCategories(ctx context.Context) ([]Category, error)
	GetAllProductByFilter(ctx context.Context, arg GetAllProductByFilterParams) ([]GetAllProductByFilterRow, error)
	GetAllUser(ctx context.Context) ([]User, error)
	GetAllUserV2(ctx context.Context, arg GetAllUserV2Params) ([]User, error)
	GetByUuid(ctx context.Context, userUuid pgtype.UUID) (User, error)
	GetImagesByProductId(ctx context.Context, id int32) ([]string, error)
	GetProductByCategoryId(ctx context.Context, id int32) ([]GetProductByCategoryIdRow, error)
	GetProductById(ctx context.Context, id int32) (Product, error)
	GetProductBySlug(ctx context.Context, slug string) (GetProductBySlugRow, error)
	SaveAndUploadImg(ctx context.Context, arg SaveAndUploadImgParams) (ProductImage, error)
	SoftDeleteUser(ctx context.Context, userUuid pgtype.UUID) (User, error)
	UpdateCart(ctx context.Context, arg UpdateCartParams) (Cart, error)
	UpdateThumbnail(ctx context.Context, arg UpdateThumbnailParams) (Product, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
