// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountProduct(ctx context.Context, arg CountProductParams) (int64, error)
	CountUser(ctx context.Context, arg CountUserParams) (int64, error)
	CreateCategory(ctx context.Context, name string) (Category, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	FindByEmail(ctx context.Context, email string) (User, error)
	GetAll(ctx context.Context) ([]Brand, error)
	GetAllCategories(ctx context.Context) ([]Category, error)
	GetAllProductByFilter(ctx context.Context, arg GetAllProductByFilterParams) ([]Product, error)
	GetAllUser(ctx context.Context) ([]User, error)
	GetAllUserV2(ctx context.Context, arg GetAllUserV2Params) ([]User, error)
	GetByUuid(ctx context.Context, userUuid pgtype.UUID) (User, error)
	GetProductById(ctx context.Context, id int32) (Product, error)
	SaveAndUploadImg(ctx context.Context, arg SaveAndUploadImgParams) (ProductImage, error)
	SoftDeleteUser(ctx context.Context, userUuid pgtype.UUID) (User, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
