// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUser = `-- name: CountUser :one
SELECT count(*)
FROM users
WHERE created_at IS NOT NULL
  AND (
    $1::text = ''
    OR name ILIKE '%' || $1 || '%'
    OR email ILIKE '%' || $1 || '%'
    )
  AND (
    $2::text = '' OR role = $2
    )
  AND (
    $3::text = ''
    OR is_active = $4::bool
    )
`

type CountUserParams struct {
	Search         string `json:"search"`
	Role           string `json:"role"`
	IsActiveFilter string `json:"is_active_filter"`
	IsActive       bool   `json:"is_active"`
}

func (q *Queries) CountUser(ctx context.Context, arg CountUserParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUser,
		arg.Search,
		arg.Role,
		arg.IsActiveFilter,
		arg.IsActive,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (name,email,password,phone,address,role)
values ($1,$2,$3,$4,$5,$6)
returning id, name, email, password, phone, address, role, is_active, created_at, updated_at, user_uuid
`

type CreateUserParams struct {
	Name     string  `json:"name"`
	Email    string  `json:"email"`
	Password string  `json:"password"`
	Phone    *string `json:"phone"`
	Address  *string `json:"address"`
	Role     *string `json:"role"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Name,
		arg.Email,
		arg.Password,
		arg.Phone,
		arg.Address,
		arg.Role,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.Phone,
		&i.Address,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserUuid,
	)
	return i, err
}

const findByEmail = `-- name: FindByEmail :one
select id, name, email, password, phone, address, role, is_active, created_at, updated_at, user_uuid from users
where email = $1
`

func (q *Queries) FindByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, findByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.Phone,
		&i.Address,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserUuid,
	)
	return i, err
}

const getAllUser = `-- name: GetAllUser :many
SELECT id, name, email, password, phone, address, role, is_active, created_at, updated_at, user_uuid FROM users
`

func (q *Queries) GetAllUser(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, getAllUser)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Password,
			&i.Phone,
			&i.Address,
			&i.Role,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserUuid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllUserV2 = `-- name: GetAllUserV2 :many
SELECT id, name, email, password, phone, address, role, is_active, created_at, updated_at, user_uuid
FROM users
WHERE created_at IS NOT NULL
  AND (
    $3::text = ''
    OR name ILIKE '%' || $3 || '%'
    OR email ILIKE '%' || $3 || '%'
    )
  AND (
    $4::text = '' OR role = $4
    )
  AND (
    $5::text = ''
    OR is_active = $6::bool
    )
order by updated_at desc 
LIMIT $1
OFFSET $2
`

type GetAllUserV2Params struct {
	Limit          int32  `json:"limit"`
	Offset         int32  `json:"offset"`
	Search         string `json:"search"`
	Role           string `json:"role"`
	IsActiveFilter string `json:"is_active_filter"`
	IsActive       bool   `json:"is_active"`
}

func (q *Queries) GetAllUserV2(ctx context.Context, arg GetAllUserV2Params) ([]User, error) {
	rows, err := q.db.Query(ctx, getAllUserV2,
		arg.Limit,
		arg.Offset,
		arg.Search,
		arg.Role,
		arg.IsActiveFilter,
		arg.IsActive,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Password,
			&i.Phone,
			&i.Address,
			&i.Role,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserUuid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getByUuid = `-- name: GetByUuid :one
select id, name, email, password, phone, address, role, is_active, created_at, updated_at, user_uuid
from users
where user_uuid = $1::uuid
`

func (q *Queries) GetByUuid(ctx context.Context, userUuid pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getByUuid, userUuid)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.Phone,
		&i.Address,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserUuid,
	)
	return i, err
}

const softDeleteUser = `-- name: SoftDeleteUser :one
update users
SET is_active = false
where user_uuid = $1::uuid
returning id, name, email, password, phone, address, role, is_active, created_at, updated_at, user_uuid
`

func (q *Queries) SoftDeleteUser(ctx context.Context, userUuid pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, softDeleteUser, userUuid)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.Phone,
		&i.Address,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserUuid,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
update users
SET name = $1::text,
    email = $2::text,
    phone = $3::text,
    address = $4::text,
    role = $5,
    is_active = $6::boolean
where user_uuid = $7::uuid
returning id, name, email, password, phone, address, role, is_active, created_at, updated_at, user_uuid
`

type UpdateUserParams struct {
	Name     string      `json:"name"`
	Email    string      `json:"email"`
	Phone    string      `json:"phone"`
	Address  string      `json:"address"`
	Role     *string     `json:"role"`
	IsActive bool        `json:"is_active"`
	UserUuid pgtype.UUID `json:"user_uuid"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.Name,
		arg.Email,
		arg.Phone,
		arg.Address,
		arg.Role,
		arg.IsActive,
		arg.UserUuid,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.Phone,
		&i.Address,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserUuid,
	)
	return i, err
}
