CREATE EXTENSION IF NOT EXISTS pg_trgm;

ALTER TABLE users
    ADD COLUMN IF NOT EXISTS name_search TEXT GENERATED ALWAYS AS (LOWER(name)) STORED,
    ADD COLUMN IF NOT EXISTS email_search TEXT GENERATED ALWAYS AS (LOWER(email)) STORED;