name: CI/CD Enterprise Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/doanvuduy170921/nines-shop:latest

  deploy:
    needs: docker
    runs-on: self-hosted
    steps:
      - name: Checkout code on VPS runner
        uses: actions/checkout@v4

      - name: Generate production .env file securely from GitHub Secrets
        run: |
            cd infra
            cat << 'EOF' > .env
            DB_HOST=postgres-db
            DB_PORT=5432
            DB_USER=${{ secrets.DB_USER }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            DB_NAME=${{ secrets.DB_NAME }}
            REDIS_HOST=redis-server
            REDIS_PORT=6379
            EOF

      - name: Pull latest image and deploy via Docker Compose (Zero-Downtime update)
        run: |
          cd infra
          
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          
          docker compose -f docker-compose.prod.yml pull
          docker compose -f docker-compose.prod.yml up -d --remove-orphans
          
          docker image prune -f